/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const VoiceCommand = IDL.Record({
  'command' : IDL.Text,
  'timestamp' : Time,
});
export const Review = IDL.Record({
  'name' : IDL.Text,
  'reviewText' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat8,
  'location' : IDL.Text,
});
export const ControlState = IDL.Record({
  'wifiOn' : IDL.Bool,
  'volume' : IDL.Nat8,
  'brightness' : IDL.Nat8,
  'dndOn' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addCommand' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat8, IDL.Text], [], []),
  'getAllCommands' : IDL.Func([], [IDL.Vec(VoiceCommand)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCurrentState' : IDL.Func([], [IDL.Opt(ControlState)], ['query']),
  'updateControlState' : IDL.Func(
      [IDL.Nat8, IDL.Nat8, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const VoiceCommand = IDL.Record({ 'command' : IDL.Text, 'timestamp' : Time });
  const Review = IDL.Record({
    'name' : IDL.Text,
    'reviewText' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat8,
    'location' : IDL.Text,
  });
  const ControlState = IDL.Record({
    'wifiOn' : IDL.Bool,
    'volume' : IDL.Nat8,
    'brightness' : IDL.Nat8,
    'dndOn' : IDL.Bool,
  });
  
  return IDL.Service({
    'addCommand' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat8, IDL.Text], [], []),
    'getAllCommands' : IDL.Func([], [IDL.Vec(VoiceCommand)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCurrentState' : IDL.Func([], [IDL.Opt(ControlState)], ['query']),
    'updateControlState' : IDL.Func(
        [IDL.Nat8, IDL.Nat8, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };