/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ControlState {
  'wifiOn' : boolean,
  'volume' : number,
  'brightness' : number,
  'dndOn' : boolean,
}
export interface Review {
  'name' : string,
  'reviewText' : string,
  'timestamp' : Time,
  'rating' : number,
  'location' : string,
}
export type Time = bigint;
export interface VoiceCommand { 'command' : string, 'timestamp' : Time }
export interface _SERVICE {
  'addCommand' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[string, string, number, string], undefined>,
  'getAllCommands' : ActorMethod<[], Array<VoiceCommand>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getCurrentState' : ActorMethod<[], [] | [ControlState]>,
  'updateControlState' : ActorMethod<
    [number, number, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];